---
title: "Untitled"
format: html
editor: visual
---

```{r}
library(dplyr)
library(data.table)
library(ggplot2)
library(patchwork)
```

```{r}
raw_dir= "/stor/scratch/Ehrlich/Users/John/histocytometry/raw_images/images_2023-08-10"
img_dirs = list.files(path= raw_dir,
                      pattern= "_SiglecH_[A-D]$",
                      full.names = TRUE) %>% 
  sort()
```

## pDCs
```{r, fig.dim = c(13,7)}
for(img_dir in img_dirs){
  print(gsub(raw_dir, "", img_dir))
  quant_file <- list.files(path= img_dir, pattern= "_mask.csv", full.names= TRUE)
  quant_df <- as.data.frame(fread(quant_file))
  
  ## Biaxial plots 
  B220_v_CD11c <- ggplot(quant_df) +
    aes(x= B220_intensity_median, y= CD11c_intensity_median) +
    geom_point()
  
  B220_v_SiglecH <- ggplot(quant_df) +
    aes(x= B220_intensity_median, y= SiglecH_intensity_median) +
    geom_point() 
  
  CD11c_v_SiglecH <- ggplot(quant_df) +
    aes(x= CD11c_intensity_median, y= SiglecH_intensity_median) +
    geom_point() 
  
  combo_plot <- (B220_v_CD11c + B220_v_SiglecH + CD11c_v_SiglecH)
  plot(combo_plot)
  
  ## Distributions 
  B220_dist <- ggplot(quant_df) + 
    aes(B220_intensity_median) +
    geom_histogram(bins= 50)
  
  CD11c_dist <- ggplot(quant_df) + 
    aes(CD11c_intensity_median) +
    geom_histogram(bins= 50)
  
  SiglecH_dist <- ggplot(quant_df) + 
    aes(SiglecH_intensity_median) +
    geom_histogram(bins= 50)
  
  dist_plots <- (B220_dist + CD11c_dist + SiglecH_dist)
  plot(dist_plots)
}

```
